services:
  app:
    container_name: mufc-booking-v2
    #build: .
    #image: javimosch/mufc-booking-v2
    image: node:20.17.0-alpine
    working_dir: /app
    ports:
      - "5082:3000"
    volumes:
      - .:/app
    env_file:
      - .env.production
    command: ["npm", "run", "web"]

      
